name: Update Leaderboard

on:
  workflow_dispatch:        # Sirf API (cron-job.org) ya manual trigger ke liye

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase Admin
        run: npm install firebase-admin

      - name: Run Leaderboard Script
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node index.js
        
